<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>77806b49-2781-413b-846c-8ef86cf3a901</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="NewFolder1\**" />
    <Compile Remove="NewFolder2\**" />
    <Content Remove="NewFolder1\**" />
    <Content Remove="NewFolder2\**" />
    <EmbeddedResource Remove="NewFolder1\**" />
    <EmbeddedResource Remove="NewFolder2\**" />
    <None Remove="NewFolder1\**" />
    <None Remove="NewFolder2\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Controller\StudentController.cs" />
    <Compile Remove="IRepository\ServiceResponse..cs" />
    <Compile Remove="Properties\Class\ServiceResponse.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="C:\Users\Lezer\Documents\Aclc_Student_GearHub final\Program.cs" Link="Program.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="C:\Users\Lezer\Documents\Aclc_Student_GearHub final\appsettings.json" Link="appsettings.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.14" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.14">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
  </ItemGroup>

</Project>
